import a2s
import tkinter as tk

window = tk.Tk(className="source engine Server Info")
window.geometry("200x150")
window.resizable(width=False, height=False)
space = tk.Label(text="   IP Address   ")
space3 = tk.Label(text="   Port   ")
space4 = tk.Label(text="")
resultname = tk.Label()
resultplayer = tk.Label()
resultping = tk.Label()
ip = tk.Entry(width=20)
port = tk.Entry(width=10)
confirm = tk.Button(text="Confirm")
def handleclick(stuff):
    global result
    addres = ip.get()
    por = int(port.get())
    address = (addres, por)
    resultname.configure(text=f"This server is called {a2s.info(address).server_name}.")
    resultplayer.configure(text=f"It has {a2s.info(address).player_count} players, out of a maximum of {a2s.info(address).max_players}.")
    resultping.configure(text=f"This server's ping is {a2s.info(address).ping}ms.")
    resultname.pack()
    window.update()
    print(resultname.winfo_width())
    geomet = str(int(resultname.winfo_width()) * 3)
    print(geomet)
    window.geometry(f"{geomet}x200")
    resultplayer.pack()
    resultping.pack()
space.pack()
ip.pack()
space3.pack()
port.pack()
space4.pack()
confirm.pack()
confirm.bind("<Button-1>", handleclick)
window.mainloop()
